backend: 
  name: test-repo

media_folder: static/assets

collections:
  - name: portfolio
    label: Portfolios
    folder: src/portfolios
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }